name = "FODESystemMC"
uuid = "1f1de9d1-aca4-4c8e-afb2-c0dacbfd2c56"
authors = ["aner <4aner4@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
